In [1]:
#Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [4]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [5]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [6]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [7]:
np.searchsorted(arr ,34)#return the index where it will go

12

In [8]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [9]:
np.count_nonzero(arr1)#number of non zero

2

In [10]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [11]:
np.where(arr > 6)#return the index where this condition satisfy

(array([5, 8]),)

In [12]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [13]:
#Numpy - Byte Swapping.

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [15]:
arr.byteswap()#convert in byte

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [16]:
#Numpy - Copies &Views.

In [17]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [18]:
a = np.copy(arr)#copy in different location

In [19]:
b = arr.view()

In [20]:
b = arr

In [21]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
b[0] = 67

In [24]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [26]:
#Numpy - Matrix Library.

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5
        )

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)#identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
#Numpy - Linear Algebra

In [32]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [33]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [35]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 0]])