In [1]:
#Numpy - Array Manipulation.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))

In [4]:
arr

array([[1, 9, 1, 6],
       [3, 8, 2, 6],
       [4, 3, 4, 3]])

In [5]:
arr.reshape(6,2)

array([[1, 9],
       [1, 6],
       [3, 8],
       [2, 6],
       [4, 3],
       [4, 3]])

In [6]:
arr.reshape(2,6)

array([[1, 9, 1, 6, 3, 8],
       [2, 6, 4, 3, 4, 3]])

In [7]:
arr.reshape(2,-242342)

array([[1, 9, 1, 6, 3, 8],
       [2, 6, 4, 3, 4, 3]])

In [8]:
arr.T

array([[1, 3, 4],
       [9, 8, 3],
       [1, 2, 4],
       [6, 6, 3]])

In [9]:
arr

array([[1, 9, 1, 6],
       [3, 8, 2, 6],
       [4, 3, 4, 3]])

In [10]:
arr.flatten()

array([1, 9, 1, 6, 3, 8, 2, 6, 4, 3, 4, 3])

In [11]:
arr1 = np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[1, 9, 1, 6],
       [3, 8, 2, 6],
       [4, 3, 4, 3]])

In [16]:
np.squeeze(arr)

array([[1, 9, 1, 6],
       [3, 8, 2, 6],
       [4, 3, 4, 3]])

In [17]:
data = np.array([[1] , [2] , [3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [23]:
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.diag(arr1)##array element in diagnol

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
#Numpy - Binary Operators.

In [26]:
arr1 = np.random.randint(1,10 , (3,4))

In [27]:
arr2 = np.random.randint(1,10 , (3,4))

In [28]:
arr1

array([[9, 6, 9, 8],
       [7, 6, 4, 6],
       [2, 3, 5, 8]])

In [29]:
arr2

array([[5, 3, 6, 8],
       [3, 3, 5, 2],
       [6, 7, 6, 1]])

In [30]:
arr1+arr2

array([[14,  9, 15, 16],
       [10,  9,  9,  8],
       [ 8, 10, 11,  9]])

In [31]:
arr1*arr2

array([[45, 18, 54, 64],
       [21, 18, 20, 12],
       [12, 21, 30,  8]])

In [32]:
arr1/arr2

array([[1.8       , 2.        , 1.5       , 1.        ],
       [2.33333333, 2.        , 0.8       , 3.        ],
       [0.33333333, 0.42857143, 0.83333333, 8.        ]])

In [33]:
arr1-arr2

array([[ 4,  3,  3,  0],
       [ 4,  3, -1,  4],
       [-4, -4, -1,  7]])

In [34]:
arr1%arr2

array([[4, 0, 3, 0],
       [1, 0, 4, 0],
       [2, 3, 5, 0]])

In [35]:
arr1 ** arr2

array([[   59049,      216,   531441, 16777216],
       [     343,      216,     1024,       36],
       [      64,     2187,    15625,        8]])

In [36]:
arr1 & arr2

array([[1, 2, 0, 8],
       [3, 2, 4, 2],
       [2, 3, 4, 0]])

In [37]:
arr1

array([[9, 6, 9, 8],
       [7, 6, 4, 6],
       [2, 3, 5, 8]])

In [38]:
arr2

array([[5, 3, 6, 8],
       [3, 3, 5, 2],
       [6, 7, 6, 1]])

In [39]:
~arr1

array([[-10,  -7, -10,  -9],
       [ -8,  -7,  -5,  -7],
       [ -3,  -4,  -6,  -9]])

In [40]:
arr1|arr2

array([[13,  7, 15,  8],
       [ 7,  7,  5,  6],
       [ 6,  7,  7,  9]])

In [41]:
arr1>arr2

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False, False,  True]])

In [42]:
#Numpy - String Functions.

In [43]:
arr = np.array(['sudh' , "Kumar"])#u5 is equivalent to string

In [44]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [45]:
np.char.upper(arr)#uppercase

array(['SUDH', 'KUMAR'], dtype='<U5')

In [46]:
np.char.title(arr)#first letter uppercase

array(['Sudh', 'Kumar'], dtype='<U5')

In [47]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [48]:
#Numpy - Mathematical Functions.

In [49]:
arr1

array([[9, 6, 9, 8],
       [7, 6, 4, 6],
       [2, 3, 5, 8]])

In [50]:
np.sin(arr1)

array([[ 0.41211849, -0.2794155 ,  0.41211849,  0.98935825],
       [ 0.6569866 , -0.2794155 , -0.7568025 , -0.2794155 ],
       [ 0.90929743,  0.14112001, -0.95892427,  0.98935825]])

In [51]:
np.cos(arr1)

array([[-0.91113026,  0.96017029, -0.91113026, -0.14550003],
       [ 0.75390225,  0.96017029, -0.65364362,  0.96017029],
       [-0.41614684, -0.9899925 ,  0.28366219, -0.14550003]])

In [52]:
np.tan(arr1)

array([[-0.45231566, -0.29100619, -0.45231566, -6.79971146],
       [ 0.87144798, -0.29100619,  1.15782128, -0.29100619],
       [-2.18503986, -0.14254654, -3.38051501, -6.79971146]])

In [53]:
np.tanh(arr1)

array([[0.99999997, 0.99998771, 0.99999997, 0.99999977],
       [0.99999834, 0.99998771, 0.9993293 , 0.99998771],
       [0.96402758, 0.99505475, 0.9999092 , 0.99999977]])

In [54]:
np.log10(arr1)

array([[0.95424251, 0.77815125, 0.95424251, 0.90308999],
       [0.84509804, 0.77815125, 0.60205999, 0.77815125],
       [0.30103   , 0.47712125, 0.69897   , 0.90308999]])

In [55]:
np.exp(arr1)

array([[8.10308393e+03, 4.03428793e+02, 8.10308393e+03, 2.98095799e+03],
       [1.09663316e+03, 4.03428793e+02, 5.45981500e+01, 4.03428793e+02],
       [7.38905610e+00, 2.00855369e+01, 1.48413159e+02, 2.98095799e+03]])

In [56]:
np.sqrt(arr1)

array([[3.        , 2.44948974, 3.        , 2.82842712],
       [2.64575131, 2.44948974, 2.        , 2.44948974],
       [1.41421356, 1.73205081, 2.23606798, 2.82842712]])

In [57]:
np.power(arr1,2)

array([[81, 36, 81, 64],
       [49, 36, 16, 36],
       [ 4,  9, 25, 64]])

In [58]:
np.mean(arr1)

6.083333333333333

In [59]:
np.median(arr1)

6.0

In [60]:
np.std(arr1)

2.1778557242286634

In [61]:
np.var(arr1)

4.743055555555555

In [62]:
np.min(arr1
      )

2

In [63]:
np.max(arr1)

9