In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l) #list converted to array

In [4]:
ar #1 Dim

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2] ,[3,4]]) #2 Dim

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
a= [2,3,4]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b = np.matrix(l)#matrix is subset of array

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)#not be converted in array

matrix([[1, 2, 3, 4]])

In [16]:
a = np.array(l)

In [17]:
a


array([1, 2, 3, 4])

In [18]:
c = a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c[0] = 100

In [22]:
c

array([100,   2,   3,   4])

In [ ]:
a#c=a means pointing same variable so if any change in one results in change for both called shallow copy

array([100,   2,   3,   4])

In [23]:
d = np.copy(a)#copying in new location called decopy

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
a[1] = 400

In [27]:
a

array([100, 400,   3,   4])

In [28]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i, j : i==j , (3,3))#means 3*3 matrix and 1=1, 2=2,3=3 according to this matrix is formed

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j : i*j , (3,3))#multiplying row*column

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)#fromiter also make array

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [34]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [35]:
#Numpy - Data Types.

In [36]:
l = [2,3,4,5,6]

In [37]:
ar = np.array(l)

In [38]:
ar

array([2, 3, 4, 5, 6])

In [39]:
ar.ndim#ndim gives dimension

1

In [40]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [41]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [42]:
ar2.ndim

2

In [43]:
ar.size

5

In [44]:
ar2.size

8

In [45]:
ar

array([2, 3, 4, 5, 6])

In [46]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [47]:
ar.shape

(5,)

In [48]:
ar2.shape#2row and 4 column

(2, 4)

In [49]:
ar.dtype

dtype('int64')

In [50]:
ar2.dtype


dtype('int64')

In [51]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [52]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [53]:
ar22.dtype

dtype('float64')

In [54]:
list(range(5))

[0, 1, 2, 3, 4]

In [55]:
list(range(0.1 ,5))#can't produce floating number

TypeError: 'float' object cannot be interpreted as an integer

In [56]:
np.arange(2.3,5.6)#arange give floating number

array([2.3, 3.3, 4.3, 5.3])

In [57]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [58]:
np.linspace(1,5,10)#produce 10 data between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.zeros(5)#produce only zeros

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [62]:
ar4 = np.zeros((3,4,2,3))

In [63]:
ar4.ndim


4

In [64]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
on =np.ones((2,3,2))

In [68]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [69]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [70]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [73]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [74]:
arr = np.random.randn(3,4)#mean =0 and st dev =1

In [75]:
import pandas as pd

In [76]:
pd.DataFrame(arr)

0         1         2         3
0  1.074395  1.525016  0.636466 -1.211889
1 -0.720684  0.510700  0.033380  1.509982
2 -0.495583 -0.343999  1.753480  0.175542

In [77]:
np.random.rand(3,4)

array([[0.71574952, 0.88651711, 0.2523272 , 0.83446668],
       [0.46865276, 0.4999911 , 0.33280436, 0.13122089],
       [0.36957948, 0.74120172, 0.40356511, 0.55169195]])

In [78]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [79]:
arr = np.random.rand(3,4)

In [81]:
arr

array([[0.90301443, 0.06323951, 0.42041368, 0.49840016],
       [0.57739477, 0.27548564, 0.13311615, 0.27614726],
       [0.22629663, 0.34112089, 0.32770831, 0.7026114 ]])

In [82]:
arr.reshape(6,-1)

array([[0.90301443, 0.06323951],
       [0.42041368, 0.49840016],
       [0.57739477, 0.27548564],
       [0.13311615, 0.27614726],
       [0.22629663, 0.34112089],
       [0.32770831, 0.7026114 ]])

In [83]:
arr1 = arr.reshape(6,-134353553435)

In [84]:
arr1

array([[0.90301443, 0.06323951],
       [0.42041368, 0.49840016],
       [0.57739477, 0.27548564],
       [0.13311615, 0.27614726],
       [0.22629663, 0.34112089],
       [0.32770831, 0.7026114 ]])

In [85]:
arr1[1][1]

0.4984001631402345

In [86]:
arr1[2:5,1]

array([0.27548564, 0.27614726, 0.34112089])

In [87]:
arr = np.random.randint(1,100 , (5,5))

In [88]:
arr

array([[53, 96, 10, 96, 58],
       [97, 40, 24, 59, 18],
       [ 3, 86, 82,  9, 77],
       [67, 73, 31, 92, 73],
       [37, 79, 28, 37, 75]])

In [89]:
arr[arr>50]

array([53, 96, 96, 58, 97, 59, 86, 82, 77, 67, 73, 92, 73, 79, 75])

In [90]:
arr

array([[53, 96, 10, 96, 58],
       [97, 40, 24, 59, 18],
       [ 3, 86, 82,  9, 77],
       [67, 73, 31, 92, 73],
       [37, 79, 28, 37, 75]])

In [91]:
arr[2:4 , [1,2]]

array([[86, 82],
       [73, 31]])

In [92]:
arr[0][0] = 5000

In [93]:
arr

array([[5000,   96,   10,   96,   58],
       [  97,   40,   24,   59,   18],
       [   3,   86,   82,    9,   77],
       [  67,   73,   31,   92,   73],
       [  37,   79,   28,   37,   75]])

In [94]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [95]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [96]:
arr2


array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [97]:
arr1+arr2

array([[3, 2, 2],
       [2, 3, 4],
       [3, 4, 2]])

In [98]:
arr1-arr2

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [99]:
arr1/arr2

array([[2. , 1. , 1. ],
       [1. , 2. , 1. ],
       [0.5, 1. , 1. ]])

In [102]:
arr1 * arr2

array([[2, 1, 1],
       [1, 2, 4],
       [2, 4, 1]])

In [103]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [104]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [105]:
arr1@arr2#matrix multiplication

array([[5, 5, 5],
       [7, 7, 7],
       [5, 5, 6]])

In [106]:
arr1/0

<ipython-input-106-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [107]:
arr1 +100

array([[102, 101, 101],
       [101, 102, 102],
       [101, 102, 101]])

In [108]:
arr1**2

array([[4, 1, 1],
       [1, 4, 4],
       [1, 4, 1]])

In [109]:
#Numpy – Broadcasting.

In [110]:
arr =np.zeros((4,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
row = np.array([1,2,3,4])

In [113]:
row.shape



(4,)

In [114]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [115]:
row.T

array([1, 2, 3, 4])

In [116]:
col = np.array([[1,2,3,4]])

In [117]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [118]:
col

array([[1, 2, 3, 4]])

In [119]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
arr1 = np.random.randint(1,4 , (3,4))

In [121]:
arr1

array([[3, 2, 1, 2],
       [2, 3, 2, 1],
       [1, 1, 3, 3]])

In [122]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.73205081, 1.41421356, 1.        ],
       [1.        , 1.        , 1.73205081, 1.73205081]])

In [123]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183,  2.71828183, 20.08553692, 20.08553692]])

In [124]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.        , 0.47712125, 0.47712125]])